### PR TITLE
Added code to handle foo@*->address.

### PR DESCRIPTION
**Pull request by rbiro**
This lets you send usernames at all domains to specific addresses.  It useful for admin@\* to handle domain requests and so forth.

### CODE REVIEW

**Comment by arithmetric** [comment]
Thanks for the contribution! I like the idea here, but would like to see test coverage before merging.

**Comment by rbiro** [comment]
Added test as requested.

**Comment by darylounet** [comment]
Any news ? This is a really cool feature !

**Comment by arithmetric** [comment]
Thanks for adding the test!

**Pull request merged**
