### PR TITLE
Specify Link to SES Endpoints

### PR DESCRIPTION
**Pull request by pr1ntr**
I was having trouble with this, and it took me a bit of a time to figure out that SES has separate endpoints for inbound SMTP.

### CODE REVIEW

**Comment by jakubboucek** [comment]
Good point! But I am suggest better text:

```markdown
Also configure the DNS MX record for these domains to point to the
[SES endpoint provided according to region](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html#region-endpoints-receiving). Note use SES Receiving endpoint for MX record.
```

**Comment by pr1ntr** [comment]
I see what you mean, I'll rewrite the whole step to make more sense.

**Comment by pr1ntr** [comment]
I updated it on my end. It doesn't seem to be updating here. Weird.

**Comment by jakubboucek** [comment]
Really, interesting. It seems you have all right. Maybe temporary Github outage, or test checks delay.
Try wait.

**Comment by arithmetric** [comment]
Thanks! I'll make a few minor tweaks.

**Pull request merged**
